### ISSUE TITLE
[Package] Missing slice2js

### ISSUE THREAD

**Issue by reysam93** [JdeRobot/base#643]
slice2js is not installed when installing the debian package of dependencies for developers of the manual.

**Comment by aitormf** [comment]
Hi,
to add slice2js we need add npm dependency and install slice2js with npm. In aditition to modify all web tools to receive JdeRobot interfaces from the compiled by slice2js in each JdeRobot compilation instead of use pre-compiled.

We did not have time to add this to the version 5.4.2, we are working on it.

At the moment, you can go to kobukiViewerJS js directory and take the jderobot interfaces
